/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import dao.ManutencaoDAO;
import gerenciamento_hardware.Gerenciamento_hardware;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import model.Manutencao;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author usuario
 */
public class TelaListaManutencao extends javax.swing.JFrame {

    /** Creates new form TelaListaManutencao */
    public TelaListaManutencao() {
        initComponents();
        carregarTabela();
        
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManutencoes = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEditar2 = new javax.swing.JButton();

        btnEditar1.setText("EDITAR");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LISTAGEM DE MANUTENÇÕES");

        tblManutencoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tipo", "Data", "ID da Máquina", "ID da Peça", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblManutencoes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblManutencoes);

        btnExcluir.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar-arquivo.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEditar2.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/casa.png"))); // NOI18N
        btnEditar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipal(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnEditar2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnEditar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
    // Verifica se alguma linha foi selecionada
    int linhaSelecionada = tblManutencoes.getSelectedRow();

    if (linhaSelecionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Selecione uma manutenção para excluir!");
        return;
    }

    // Pega o ID da manutenção (coluna 0)
    int id = (int) tblManutencoes.getValueAt(linhaSelecionada, 0);

    // Confirmação do usuário
    int opcao = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente excluir a manutenção ID " + id + "?",
            "Confirmação",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (opcao == javax.swing.JOptionPane.YES_OPTION) {

        ManutencaoDAO dao = new ManutencaoDAO();

        if (dao.excluir(id)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Manutenção excluída com sucesso!");
            carregarTabela(); // atualiza a tabela
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Erro ao excluir manutenção!");
        }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int linhaSelecionada = tblManutencoes.getSelectedRow();

if (linhaSelecionada == -1) {
    javax.swing.JOptionPane.showMessageDialog(this,
            "Selecione uma manutenção para editar!");
    return;
}

Manutencao m = new Manutencao();

m.setId((int) tblManutencoes.getValueAt(linhaSelecionada, 0));
m.setTipo((String) tblManutencoes.getValueAt(linhaSelecionada, 1));

// CONVERSÃO CORRETA DA DATA
String dataTexto = tblManutencoes.getValueAt(linhaSelecionada, 2).toString();
SimpleDateFormat br = new SimpleDateFormat("dd/MM/yyyy");
SimpleDateFormat iso = new SimpleDateFormat("yyyy-MM-dd");

java.util.Date du = null;
        try {
            du = br.parse(dataTexto);
        } catch (ParseException ex) {
            Logger.getLogger(TelaListaManutencao.class.getName()).log(Level.SEVERE, null, ex);
        }
java.sql.Date data = java.sql.Date.valueOf(iso.format(du));

m.setData(data);

m.setMaquinaId((int) tblManutencoes.getValueAt(linhaSelecionada, 3));
m.setPeca((int) tblManutencoes.getValueAt(linhaSelecionada, 4));
m.setDescricao((String) tblManutencoes.getValueAt(linhaSelecionada, 5));

new TelaManutencao(m, this).setVisible(true);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void btnMenuPrincipal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipal
        this.dispose();
        new Gerenciamento_hardware().abrirMenu();
        
    }//GEN-LAST:event_btnMenuPrincipal
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListaManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListaManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListaManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListaManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListaManutencao().setVisible(true);
            }
        });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnEditar2;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManutencoes;
    // End of variables declaration//GEN-END:variables

    
    public void carregarTabela() {

    DefaultTableModel modelo = (DefaultTableModel) tblManutencoes.getModel();
    modelo.setRowCount(0);

    ManutencaoDAO dao = new ManutencaoDAO();
    List<Manutencao> lista = dao.listar();
 SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");  
    for (Manutencao m : lista) {
        
        modelo.addRow(new Object[]{
            m.getId(),
            m.getTipo(),
            sdf.format(m.getData()),
            m.getMaquinaId(),
            m.getPeca(),
            m.getDescricao()
        });
}

    }
}



